unique_ids:
  assets:
    standard-page.html: BBVZ6ZGC2FNCMRW5BVJQUIBOLB4VK76U
    theme.css: AJGOB5QTSL6FY2XA3CJNYIYBPZ7BTK3I
  forms:
    Startseite: WUKYFUSJLTDIQA7CFZWKLWDRCE5MRMJN
    Startseite.RowTemplate1: '1729073614575181545006632.51193'
  modules: {}
  scripts: {}
  server_modules:
    Database_Server: '1728465423128893394152348.3517'
