unique_ids:
  assets:
    standard-page.html: BBVZ6ZGC2FNCMRW5BVJQUIBOLB4VK76U
    theme.css: AJGOB5QTSL6FY2XA3CJNYIYBPZ7BTK3I
  forms:
    Form1: WUKYFUSJLTDIQA7CFZWKLWDRCE5MRMJN
  modules: {}
  scripts: {}
  server_modules: {}
